# Site
repository: wantaekchoi/wantaekchoi.github.io
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 최완택
title: 개발자
email: wantaekchoi@gmail.com
# website: https://choiwantaek.tistory.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: wantaekv0_0_1
github_username:  wantaekchoi
# instagram_username: _wantaek
linkedin_username: wantaek

# Additional icon links
additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  블록체인 관련 서비스를 개발하고 있습니다. 블록체인 기술과 관련 비즈니스에 흥미가 있습니다.

  이더리움 및 EOSIO 기반 블록체인에 컨트렉트와 DApp을 작성하고 배포했습니다.

  생소한 기술에 문서를 보고 빠르게 습득합니다. 관련 키워드를 찾아내고 상대방에게 안내할 수 있습니다.

  보안이나 블록체인에서 활용되는 다양한 cryto 알고리즘을 파악하고 사용합니다.

  오픈 소스 프로젝트에 기여할 기회를 노리고 있습니다. 백엔드 서버 개발에 흥미를 갖고 공부 중입니다.

  리눅스 개발환경에 익숙하고, git 및 git 플랫폼을 활용한 버전 관리에 능숙합니다.

content:
  - title: Project # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: OmniOne Badge
        sub_title: 라온시큐어(주)
        caption: 2023. 00. - 2023. 00.
        link: https://badge.omnione.net
        quote: >
          블록체인 기반 OpenBadge 발행 서비스
        description: | # this will include new lines to allow paragraphs
          JSON 형식 인증서를 발행 및 호스팅, 디스플레이 하는 서비스입니다.

          OpenBadge 2.0에 Blockcerts 확장을 구현했습니다.

          - 발행: 인증서의 Merkle root를 블록체인 트렌젝션 값으로 싣어 burn address로 송금합니다.
          - 검증: 블록체인 트렌젝션을 조회하여 인증서에 Merkle tree를 검증합니다.

          Alchemy Provider를 사용하고, NestJS REST API 백엔드 서버와 NextJS 웹 프론트엔드를 작성했습니다.

          compose 파일을 작성하여 AWS EC2상에 docker로 배포했습니다.

          다양한 환경(로컬-개발-테스트-운영)에 따른 빌드 및 배포를 스크립트를 작성하여 자동화 했습니다.

      - layout: left
        title: OmniOne NFT Marketplace
        sub_title: 라온시큐어(주)
        caption: 2022. 00. - 2023. 00.
        link: https://nft.omnione.net
        quote: >
          NFT 마켓플레이스
        description: | # this will include new lines to allow paragraphs
          EOSIO 기반 블록체인인 OmniOne 블록체인 컨트렉트를 작성했습니다. (EOSIO-CPP)

          NFT 서비스를 위해 전송(+ 발행, 폐기)와 approve, setApproveForAll 기능을 구현했습니다.

          컨트렉트 결함 방지를 위해 테스트 코드를 작성했습니다. (커버리지 100%)

          백엔드 서버 개발자를 위해 xxx 분량의 README를 작성하고, 데이터 인코딩을 작성하여 전달 했습니다.

          운영을 위한 관리 기능을 구현하고, admin 웹 페이지를 작성하여 운영 담당자가 문제 상황에 사용하도록 가이드했습니다.

      - layout: left
        title: 트러스트키
        sub_title: 주식회사 트러스트키
        caption: 2016. 00. - 2020. 00.
        quote: >
          USB 보안 키 (FIDO 지문 인증 장치)
        description: | # this will include new lines to allow paragraphs
          지문 인식 기반 FIDO2 하드웨어 보안 장치를 개발하고 보안 인증을 진행했습니다.
          - ARM Cortex-M0/M3 기반 장치 펌웨어 개발
          - 부트로더 작성, 펌웨어 무결성 검증 및 데이터 암호화
          - HID 키보드/FIDO 장치 개발, 지문 인증 포팅 및 최적화
          - FIDO U2F/UAF/2/2.1, RFC 4226(HOTP)/6238(TOTP) 개발 및 보안 인증 획득

      - layout: left
        title: NPT-Sonicure
        sub_title: (주)오스테오시스
        caption: 2020. 00. - 2020. 00.
        quote: >
          디지털 array 컨트롤 기반 체외충격파치료(ESWT) 의료기기
        description: | # this will include new lines to allow paragraphs
          치료기 장비 제어를 위한 펌웨어 개발
          - AVR 펌웨어 개발: 통신 및 FPGA 제어, 전원 제어, 부트로더 개발
          - 장비 검증 및 테스트, 양산 이관

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 라온시큐어(주)
        link: https://www.raonsecure.com
        sub_title: 블록체인기술연구소
        caption: 2022. 01. (재직 중)
        quote: >
          회사 소개 1234
        description: | # this will include new lines to allow paragraphs
          - 주요 실적 1
          - 주요 실적 2
          - 주요 업무 1
          - 주요 업무 2

      - layout: left
        title: (주)오스테오시스
        link: https://osteosys.com
        sub_title: NMD 사업부
        caption: 2022. 09. - 2021. 12. (x년 x개월)
        quote: >
          회사 소개 1234
        description: | # this will include new lines to allow paragraphs
          - 주요 실적 1
          - 주요 실적 2
          - 주요 업무 1
          - 주요 업무 2

      - layout: left
        title: 주식회사 트러스트키, (주)이더블유비엠
        link: https://www.trustkey.kr
        sub_title: 기술연구소
        caption: 2016. 10. - 2020. 09. (x년 x개월)
        quote: >
          회사 소개 1234
        description: | # this will include new lines to allow paragraphs
          - 주요 실적 1
          - 주요 실적 2
          - 주요 업무 1
          - 주요 업무 2


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 한국산업기술대학교
        caption: 2011. 03. - 2017. 02.
        sub_title: 컴퓨터공학과
        description: | # this will include new lines to allow paragraphs
          이수과목 및 연구내용 ..

      - layout: left
        title: 안양고등학교
        caption: 2008. 03. - 2011. 02.
        sub_title: 인문계열 # 고등학교 학력 사항을 넣어야 하는가?

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
